### ISSUE TITLE
v1.2.2: NullPointerException, GameLogic.purchaseField

### ISSUE THREAD

**Issue by algorythm** [hold11/CDIO_del3#88]
Exception:
```
Exception in thread "main" java.lang.NullPointerException
	at models.GameLogic.purchaseField(GameLogic.java:80)
	at Main.main(Main.java:33)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
```

```
--------------- Player 2 ---------------
Fields owned by Player 2
 * South Citadel
 * Huts in the Mountain
 * Privateer Armada
 * Cold Desert
 * Mountain Village
 * Tower

Player 2's turn. Current balance: 9250
Player 2 rolled 4 and 1 (5).
Player 2 landed on The Pit
Player 2's balance is now 8750
The Pit is currently owned by Player 1.
The rent is 500. Player 2's balance is now 8750.


--------------- Player 1 ---------------
Fields owned by Player 1
 * The Werewall
 * Sea Grover
 * Black Cave
 * The Pit
 * Crater
 * Palace Gates
 * Castle

Player 1's turn. Current balance: 2200
Player 1 rolled 6 and 1 (7).
Player 1 landed on Cold Desert
Player 1's balance is now 1500
Cold Desert is currently owned by Player 2.
The rent is 700. Player 1's balance is now 1500.
Player 2 recieved 700 from Player 1. Player 2's balance is now 9450


--------------- Player 2 ---------------
Fields owned by Player 2
 * South Citadel
 * Huts in the Mountain
 * Privateer Armada
 * Cold Desert
 * Mountain Village
 * Tower

Player 2's turn. Current balance: 9450
Player 2 rolled 3 and 1 (4).
Player 2 landed on Sea Grover
Player 2's balance is now 8950
Sea Grover is currently owned by Player 1.
The rent is 500. Player 2's balance is now 8950.
Player 1 recieved 500 from Player 2. Player 1's balance is now 2000


--------------- Player 1 ---------------
Fields owned by Player 1
 * The Werewall
 * Sea Grover
 * Black Cave
 * The Pit
 * Crater
 * Palace Gates
 * Castle

Player 1's turn. Current balance: 2000
Player 1 rolled 3 and 3 (6).
Player 1 landed on Tower
Player 1's balance is now 0
Sea Grover is currently owned by null.
The rent is 500. Player 2's balance is now 12150.
```

**Comment by algorythm** [comment]
Works:
```
--------------- Player 1 ---------------
Fields owned by Player 1
 * The Werewall
 * Huts in the Mountain
 * Mountain
 * The Pit
 * The Buccaneers
 * Palace Gates
 * Second Sail
 * Black Cave

Player 1's turn. Current balance: 1551
Player 1 rolled 3 and 2 (5).
Player 1 landed on Castle
Player 1's balance is now 0
Black Cave is currently owned by null.
The rent is 1000. Player 2's balance is now 6460.
Player 2 has lost the game.



------------------------------


Player 2 has won the game. Balance: 6460

Process finished with exit code 0
```
